---
title: "Nested Machine Learning Workflows"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to my practice workbook.

In this occasion I will practice the **Nested Machine Learning Workflows** using R
and  other packages like purrr or tidy packages.  An approach to keep all related things together in one place; in this
time in one single data frame for ease of analysis.

This is taken from the website of [Jared Wilber](https://www.jwilber.me), [from this section](https://www.jwilber.me/nest).  
Once again a big hat to Jeremy Singer-Vine and his Data is Plural newsletter.

The post is divided in the following sections:

  a. [Introduction](introduction.html)
  b. [Tidy data review](tidy-data-review.html)
  c. [Feature transformation](feature-transformation.html)
  d. [Machine learning](machine-learning.html)
  e. Putting together feature transformation and machine learning
  f. Results
  g. Conclusions
